'use client';
import {useEffect,type RefObject} from 'react';
import type {State,ParsedCapture} from '@/lib/types';
type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown|Promise<unknown>};
type Registry={registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
/** Optional page-scoped tools. Every write goes through the visible capture preview. */
export function useAgentTools(state:RefObject<State|null>,enabled:boolean,onPreview:(text:string,parsed:ParsedCapture)=>void){
useEffect(()=>{if(!enabled)return;const registry=(document as Document&{modelContext?:Registry}).modelContext;if(!registry?.registerTool)return;const lifecycle=new AbortController();
const tools:Tool[]=[{
name:'daybook_search_thoughts',title:'Search Daybook thoughts',description:'Read matching cards from the signed-in journal. Does not change any cards.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object')throw new Error('Expected an object');const query=(input as {query?:unknown}).query??'';if(typeof query!=='string'||query.length>200)throw new Error('Query must be text up to 200 characters');const cards=(state.current?.cards||[]).filter(c=>c.status!=='archived'&&(c.title+' '+c.plainText).toLowerCase().includes(query.toLowerCase()));return {count:cards.length,cards:cards.slice(0,20).map(c=>({id:c.id,title:c.title,kind:c.kind,status:c.status,plannedDate:c.plannedDate,dueDate:c.dueDate}))};}
},{name:'daybook_preview_capture',title:'Preview a Daybook capture',description:'Interpret text and open the editable capture preview. This does not save a card or create a calendar event; the user saves in the visible dialog.',inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:10000}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input){const text=input&&typeof input==='object'?(input as {text?:unknown}).text:undefined;if(typeof text!=='string'||!text.trim()||text.length>10000)throw new Error('Provide a thought of 1–10,000 characters');const response=await fetch('/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const parsed=await response.json();if(!response.ok)throw new Error(parsed.error);onPreview(text,parsed);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {stage:'preview',title:parsed.title,kind:parsed.kind,plannedDate:parsed.plannedDate,dueDate:parsed.dueDate,saved:false};}}];
for(const tool of tools){try{void Promise.resolve(registry.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* The interface still works in browsers without this experimental API. */}}
return()=>lifecycle.abort();},[enabled,state]);
}
