'use client';
import {useState} from 'react';
import {CalendarDays,ArrowRight,Hash,Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Button} from './ui/button';
import {type ParsedCapture,type State,type Card,textDoc,makeCard} from '@/lib/types';
import {miniSummary} from '@/lib/summary';
export function CaptureDialog({parsed,state,onClose,onCreate}:{parsed:ParsedCapture;state:State;onClose:()=>void;onCreate:(card:Card)=>Promise<void>}){
const [value,setValue]=useState(parsed),[saving,setSaving]=useState(false),[error,setError]=useState('');
return <Dialog open onOpenChange={open=>{if(!open&&!saving)onClose();}}><DialogContent className="capture-dialog"><div className="dialog-icon"><Sparkles size={24}/></div><DialogTitle>A place for this thought</DialogTitle><DialogDescription>Here’s what I understood. Adjust anything before saving.</DialogDescription><p className="field-hint">Your card will get a short summary from its content.</p><div className="field-grid"><label>Journal type<select value={value.kind} onChange={e=>setValue({...value,kind:e.target.value as Card['kind']})}><option value="note">– Note / idea</option><option value="task">• Task</option><option value="event">○ Event</option></select></label><label>Repeat<select value={value.recurrence} onChange={e=>setValue({...value,recurrence:e.target.value as Card['recurrence']})}><option value="none">None</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label><CalendarDays size={14}/>Planned for<input type="date" value={value.plannedDate||''} onChange={e=>setValue({...value,plannedDate:e.target.value||null})}/></label><label>Due by<input type="date" value={value.dueDate||''} onChange={e=>setValue({...value,dueDate:e.target.value||null})}/></label><label>Time<input type="time" value={value.time||''} onChange={e=>setValue({...value,time:e.target.value||null})}/></label></div>{value.ambiguous&&<p className="notice">Please check the date and time. Your wording leaves room for interpretation.</p>}<div className="tag-suggestions"><span><Hash size={15}/>Tags</span><div>{state.tags.filter(t=>!t.archived).map(t=><button key={t.id} style={{color:t.color,borderColor:value.tags.includes(t.id)?t.color:'',background:value.tags.includes(t.id)?t.color+'15':''}} aria-pressed={value.tags.includes(t.id)} className={'tag-option '+(value.tags.includes(t.id)?'selected':'')} onClick={()=>setValue({...value,tags:value.tags.includes(t.id)?value.tags.filter(id=>id!==t.id):[...value.tags,t.id]})}># {t.name}{value.suggestedTags.includes(t.id)&&!value.tags.includes(t.id)&&<span>suggested</span>}</button>)}</div></div><blockquote className="capture-original">{parsed.original}</blockquote>{error&&<p className="error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={onClose} disabled={saving}>Keep editing</Button><Button disabled={saving} onClick={async()=>{setSaving(true);try{await onCreate(makeCard({...value,title:miniSummary(value.original),content:textDoc(value.original),plainText:value.original}));}catch(e){setError(e instanceof Error?e.message:'Could not save');}finally{setSaving(false);}}}>{saving?'Saving…':'Save thought'}<ArrowRight size={16}/></Button></div></DialogContent></Dialog>;
}
