import {makeCard,textDoc,localDate,defaultViewPreferences,type State} from './types';
export function demoState():State {
const today=localDate();const tomorrow=localDate(new Date(Date.now()+86400000));
return {version:1,preferences:{...defaultViewPreferences},tags:[{id:'personal',name:'personal',color:'#a23b72',aliases:[],archived:false},{id:'ideas',name:'ideas',color:'#2c7a7b',aliases:['idea'],archived:false},{id:'errands',name:'errands',color:'#9a5b13',aliases:['shopping'],archived:false},{id:'work',name:'work',color:'#6458a6',aliases:[],archived:false}],collections:[{id:'little-projects',name:'Little projects'},{id:'life-admin',name:'Life admin'}],boardTags:['personal','ideas','errands','work'],reflections:{},cards:[
makeCard({id:'welcome',title:'A little room for everything in your head',kind:'note',tags:['personal'],plainText:'Capture first. Make a plan when you’re ready. These sample cards are yours to edit or archive.',content:textDoc('Capture first. Make a plan when you’re ready. These sample cards are yours to edit or archive.')}),
makeCard({id:'garden',title:'A tiny dashboard for the garden',kind:'note',tags:['ideas'],collectionId:'little-projects',plainText:'Track what’s growing, save planting notes, and remember when to water. Start with just one bed.',content:textDoc('Track what’s growing, save planting notes, and remember when to water. Start with just one bed.'),priority:true}),
makeCard({id:'groceries',title:'Go to the grocery store',kind:'task',tags:['errands'],plannedDate:tomorrow,energy:'low',effort:30,plainText:'Something easy for dinner. Coffee for the morning.',content:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Something easy for dinner.'}]},{type:'taskList',content:[{type:'taskItem',attrs:{checked:false},content:[{type:'paragraph',content:[{type:'text',text:'Coffee'}]}]},{type:'taskItem',attrs:{checked:false},content:[{type:'paragraph',content:[{type:'text',text:'Fresh fruit'}]}]}]}]}}),
makeCard({id:'website',title:'Sketch the first page of my website',kind:'task',tags:['work'],plannedDate:today,focus:true,effort:15,energy:'medium',nextAction:'Draw three boxes on paper.',plainText:'Keep it small. A rough sketch is enough for today.',content:textDoc('Keep it small. A rough sketch is enough for today.')}),
makeCard({id:'walk',title:'A walk without my phone',kind:'task',tags:['personal'],plannedDate:today,focus:true,effort:20,energy:'low',plainText:'A little space to think.',content:textDoc('A little space to think.')}),
makeCard({id:'dinner',title:'Dinner with friends',kind:'event',tags:['personal'],plannedDate:tomorrow,time:'19:00',duration:90,plainText:'Bring something to share.',content:textDoc('Bring something to share.')}),
]};}
