import {z} from 'zod';
import {equal} from './auth';
import {HttpError,transact,readState} from './store';
import {interpret} from './capture';
import {localDate,makeCard,textDoc,formatDate} from './types';
const messageSchema=z.object({guid:z.string().min(1).max(200),text:z.string().min(1).max(10000),chatGuid:z.string().min(1).max(200),sender:z.string().min(1).max(200),isFromMe:z.boolean().default(false)});
export function normalizeMessage(body:unknown){const normalized=messageSchema.safeParse(body);if(normalized.success)return normalized.data;if(!body||typeof body!=='object')throw new HttpError(400,'Invalid message');const b=body as Record<string,unknown>;if(b.type!=='new-message')throw new HttpError(400,'Only new-message events are accepted');const d=b.data as {guid?:string;text?:string;chats?:{guid:string}[];handle?:{address:string};isFromMe?:boolean;associatedMessageGuid?:string};if(d?.associatedMessageGuid)throw new HttpError(400,'Reactions are not captured');return messageSchema.parse({guid:d?.guid,text:d?.text,chatGuid:d?.chats?.[0]?.guid,sender:d?.handle?.address,isFromMe:d?.isFromMe});}
export function checkMessageAccess(token:string,m:ReturnType<typeof normalizeMessage>){if(!process.env.IMESSAGE_TOKEN||!process.env.IMESSAGE_CHAT_GUID||!process.env.IMESSAGE_ALLOWED_SENDERS)throw new HttpError(503,'iMessage capture is not configured');if(!equal(token,process.env.IMESSAGE_TOKEN))throw new HttpError(401,'Invalid receiver token');if(m.isFromMe||m.chatGuid!==process.env.IMESSAGE_CHAT_GUID||!process.env.IMESSAGE_ALLOWED_SENDERS.split(',').map(s=>s.trim().toLowerCase()).includes(m.sender.toLowerCase()))throw new HttpError(403,'Message is outside the approved capture conversation');}
export async function receiveMessage(m:ReturnType<typeof normalizeMessage>){const parsed=await interpret(m.text,(await readState()).tags);return transact(async(s,tx)=>{const existing=await tx.findMessage(m.guid);if(existing!==null)return {duplicate:true,cardId:existing,reply:'Already captured.'};const text=m.text.trim();let cardId='',reply='';
if(/^(today|what[’']?s (on )?today\??)$/i.test(text)){const cards=s.cards.filter(c=>c.status==='open'&&(c.focus||c.plannedDate===localDate()||(c.dueDate&&c.dueDate<=localDate())));reply=cards.length?cards.slice(0,10).map(c=>`${c.id.slice(0,8)} · ${c.title}`).join('\n'):'Your Today list is clear.';}
else if(/^done\s+/i.test(text)){const id=text.replace(/^done\s+/i,'').trim();const matches=s.cards.filter(c=>c.id.startsWith(id));if(matches.length!==1)throw new HttpError(400,'Use the unique eight-character card ID from Today');const c=matches[0];if(c.recurrence!=='none')throw new HttpError(400,'Complete repeating tasks in the app for now');c.status='done';c.updatedAt=new Date().toISOString();cardId=c.id;reply=`Completed: ${c.title}`;}
else {const c=makeCard({...parsed,content:textDoc(m.text),plainText:m.text,tags:parsed.tags});s.cards.unshift(c);cardId=c.id;reply=`Saved: ${c.title}${c.plannedDate?' · '+formatDate(c.plannedDate):''}${c.dueDate?' · due '+formatDate(c.dueDate):''}${parsed.ambiguous?' — check the interpreted date in Daybook.':''}\nID: ${c.id.slice(0,8)}`;}
await tx.putMessage(m.guid,cardId);return {duplicate:false,cardId,reply};});}
